name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    uses: brunocvs7/ds-workflows/.github/workflows/python-ci.yml@v1
    with:
      run-conformance: false   # não é um projeto DS
